local muos = {
  SD1_PATH = "/mnt/mmc",
  SD2_PATH = "/mnt/sdcard",
  CATALOGUE = "/run/muos/storage/info/catalogue",
  ASSIGN_JSON = "/opt/muos/share/info/assign/assign.json",
  ASSIGN_DIR = "/opt/muos/share/info/assign",
  CORE_DIR = "/opt/muos/share/info/core",
  platforms = {
    ["amstradcpc"] = "Amstrad",
    ["arcade"] = "Arcade",
    ["arduboy"] = "Arduboy",
    ["atari2600"] = "Atari 2600",
    ["atari5200"] = "Atari 5200",
    ["atari7800"] = "Atari 7800",
    ["atarijaguar"] = "Atari Jaguar",
    ["atarilynx"] = "Atari Lynx",
    ["atarist"] = "Atari ST-STE-TT-Falcon",
    ["wonderswan"] = "Bandai WonderSwan-Color",
    ["wonderswancolor"] = "Bandai WonderSwan-Color",
    -- "CHIP-8",
    -- "Cannonball",
    -- "Cave Story",
    -- "ChaiLove",
    ["coleco"] = "ColecoVision",
    ["amiga"] = "Commodore Amiga",
    ["c128"] = "Commodore C128",
    ["c64"] = "Commodore C64",
    -- "Commodore CBM-II",
    -- "Commodore PET",
    ["vic20"] = "Commodore VIC-20",
    ["pc"] = "DOS",
    -- "Dinothawr",
    -- "Doom",
    ["PORTS"] = "External - Ports",
    ["channelf"] = "Fairchild ChannelF",
    -- "Flashback",
    ["vectrex"] = "GCE-Vectrex",
    ["gameandwatch"] = "Handheld Electronic - Game and Watch",
    ["j2me"] = "Java J2ME",
    ["lowresnx"] = "Lowres NX",
    -- "Lua Engine",
    ["coleco_"] = "MSX-SVI-ColecoVision-SG1000",
    ["megaduck"] = "Mega Duck - Cougar Boy",
    ["intellivision"] = "Mattel - Intellivision",
    ["msx"] = "Microsoft - MSX",
    -- "Mr. Boom",
    ["pcengine"] = "NEC PC Engine",
    ["pcenginecd"] = "NEC PC Engine CD",
    ["pcengine_"] = "NEC PC Engine SuperGrafx",
    ["pcfx"] = "NEC PC-FX",
    ["pc88"] = "NEC PC-8000 - PC-8800 series",
    ["pc98"] = "NEC PC98",
    ["nds"] = "Nintendo DS",
    ["gb"] = "Nintendo Game Boy",
    ["gba"] = "Nintendo Game Boy Advance",
    ["gbc"] = "Nintendo Game Boy Color",
    ["n64"] = "Nintendo N64",
    ["nes"] = "Nintendo NES - Famicom",
    ["fds"] = "Nintendo FDS",
    ["snes"] = "Nintendo SNES - SFC",
    ["pokemini"] = "Nintendo Pokemon Mini",
    ["virtualboy"] = "Nintendo Virtual Boy",
    ["openbor"] = "OpenBOR",
    ["pico8"] = "PICO-8",
    ["palm"] = "Palm OS",
    ["cdi"] = "Philips CDi",
    -- "Quake",
    ["easyrpg"] = "RPG Maker 2000 - 2003",
    -- "Rick Dangerous",
    -- "Root",
    ["neogeo"] = "SNK Neo Geo",
    ["neogeocd"] = "SNK Neo Geo CD",
    ["ngp"] = "SNK Neo Geo Pocket - Color",
    ["ngpc"] = "SNK Neo Geo Pocket - Color",
    ["scummvm"] = "ScummVM",
    ["sega32x"] = "Sega 32X",
    ["naomi"] = "Sega Atomiswave Naomi",
    ["atomiswave"] = "Sega Atomiswave Naomi",
    ["dreamcast"] = "Sega Dreamcast",
    ["gamegear"] = "Sega Game Gear",
    ["mastersystem"] = "Sega Master System",
    ["segacd"] = "Sega Mega CD - Sega CD",
    ["megadrive"] = "Sega Mega Drive - Genesis",
    ["mastersystem_"] = "Sega SG-1000",
    ["saturn"] = "Sega Saturn",
    ["x1"] = "Sharp X1",
    ["x68000"] = "Sharp X68000",
    ["zx81"] = "Sinclair ZX 81",
    ["zxspectrum"] = "Sinclair ZX Spectrum",
    ["psx"] = "Sony PlayStation",
    ["psp"] = "Sony Playstation Portable",
    ["tic80"] = "TIC-80",
    -- "Texas Instruments TI-83",
    ["3do"] = "The 3DO Company - 3DO",
    ["uzebox"] = "Uzebox",
    -- "VeMUlator",
    ["vircon32"] = "Vircon32",
    ["wasm4"] = "WASM-4",
    ["supervision"] = "Watara Supervision",
    -- "Wolfenstein 3D",
  },
  assignment = {
    ["Amstrad"] = "amstradcpc",
    ["Arcade"] = "arcade",
    ["Arduboy"] = "arduboy",
    ["Atari 2600"] = "atari2600",
    ["Atari 5200"] = "atari5200",
    ["Atari 7800"] = "atari7800",
    ["Atari Jaguar"] = "atarijaguar",
    ["Atari Lynx"] = "atarilynx",
    ["Atari ST-STE-TT-Falcon"] = "atarist",
    ["Bandai WonderSwan-Color"] = "wonderswancolor",
    ["ColecoVision"] = "coleco",
    ["Commodore Amiga"] = "amiga",
    ["Commodore C128"] = "c128",
    ["Commodore C64"] = "c64",
    ["Commodore VIC-20"] = "vic20",
    ["DOS"] = "pc",
    ["External - Ports"] = "PORTS",
    ["Fairchild ChannelF"] = "channelf",
    ["GCE-Vectrex"] = "vectrex",
    ["Handheld Electronic - Game and Watch"] = "gameandwatch",
    ["Java J2ME"] = "j2me",
    ["Lowres NX"] = "lowresnx",
    ["MSX-SVI-ColecoVision-SG1000"] = "coleco",
    ["Mattel - Intellivision"] = "intellivision",
    ["Mega Duck - Cougar Boy"] = "megaduck",
    ["Microsoft - MSX"] = "msx",
    ["NEC PC Engine"] = "pcengine",
    ["NEC PC Engine CD"] = "pcenginecd",
    ["NEC PC Engine SuperGrafx"] = "pcengine",
    ["NEC PC-FX"] = "pcfx",
    ["NEC PC98"] = "pc98",
    ["Nintendo DS"] = "nds",
    ["Nintendo Game Boy"] = "gb",
    ["Nintendo Game Boy Advance"] = "gba",
    ["Nintendo Game Boy Color"] = "gbc",
    ["Nintendo N64"] = "n64",
    ["Nintendo NES - Famicom"] = "nes",
    ["Nintendo Pokemon Mini"] = "pokemini",
    ["Nintendo SNES - SFC"] = "snes",
    ["Nintendo Virtual Boy"] = "virtualboy",
    ["OpenBOR"] = "openbor",
    ["PICO-8"] = "pico8",
    ["Palm OS"] = "palm",
    ["Philips CDi"] = "cdi",
    ["Sinclair ZX Spectrum"] = "zxspectrum",
    ["SNK Neo Geo"] = "neogeo",
    ["SNK Neo Geo CD"] = "neogeocd",
    ["SNK Neo Geo Pocket - Color"] = "ngpc",
    ["ScummVM"] = "scummvm",
    ["Sega 32X"] = "sega32x",
    ["Sega Atomiswave Naomi"] = "atomiswave",
    ["Sega Dreamcast"] = "dreamcast",
    ["Sega Game Gear"] = "gamegear",
    ["Sega Master System"] = "mastersystem",
    ["Sega Mega CD - Sega CD"] = "segacd",
    ["Sega Mega Drive - Genesis"] = "megadrive",
    ["Sega SG-1000"] = "mastersystem",
    ["Sega Saturn"] = "saturn",
    ["Sharp X1"] = "x1",
    ["Sharp X68000"] = "x68000",
    ["Sinclair ZX 81"] = "zx81",
    ["Sinclair ZX Spectrum"] = "zxspectrum",
    ["Sony PlayStation"] = "psx",
    ["Sony Playstation Portable"] = "psp",
    ["TIC-80"] = "tic80",
    ["The 3DO Company - 3DO"] = "3do",
    ["Uzebox"] = "uzebox",
    ["Vircon32"] = "vircon32",
    ["WASM-4"] = "wasm4",
    ["Watara Supervision"] = "supervision",
  },
}

return muos
